### ISSUE TITLE
problem with adding async images 

### ISSUE THREAD

**Issue by andrey-pagin** [c-villain/SwipeActions#14]
<img width="682" alt="Screenshot 2023-04-14 at 17 05 29" src="https://user-images.githubusercontent.com/46619241/232027901-f145b852-7962-4ef8-82b8-97c9f1801f81.png">
<img width="693" alt="Screenshot 2023-04-14 at 17 06 42" src="https://user-images.githubusercontent.com/46619241/232028099-96d6a908-b3f7-4a83-9871-a759972c4bdd.png">
<img width="652" alt="Screenshot 2023-04-14 at 17 07 44" src="https://user-images.githubusercontent.com/46619241/232028268-09ec7c00-7dfd-45fd-86b3-f7f3be392b17.png">

I added an async image to my SwiftUI view, but when I try to fullswipe the view, it triggers with minimum drag , and as i found content width in function measureSize() becomes 0. This issue doesn't happen without the image. How can I fix this problem?

**Comment by c-villain** [comment]
@andrey-pagin hm... thx for ur report) I'll try to find solution...

**Comment by c-villain** [comment]
@andrey-pagin anyway plz share the code how you add swipe actions to ur async image

**Comment by andrey-pagin** [comment]
> @andrey-pagin anyway plz share the code how you add swipe actions to ur async image

`public var body: some View {
        ForEach(dataModel.items) { item in
            ItemView(data: item)
                .cornerRadius(16)
                .padding(.init(top: 0, leading: 12, bottom: 0, trailing: 12))
                .background(Colors.White.one)
                .listRowSeparator(.hidden)
                .listRowInsets(EdgeInsets())
                .addFullSwipeAction(
                    menu: .slided,
                    swipeColor: Colors.Black.two,
                    swipeRole: .defaults,
                    state: $state
                ) {
                    Leading {
                        Button {
                        } label: {
                            Image(systemName: "archivebox")
                                .foregroundColor(Colors.White.one)
                        }
                        .frame(width: 60)
                        .frame(maxHeight: .infinity)
                        .contentShape(Rectangle())
                        .background(.clear)
                    }
                    Trailing {
                        Button {
                        } label: {
                            Image(systemName: "archivebox")
                                .foregroundColor(.white)
                        }
                        .frame(width: 60)
                        .frame(maxHeight: .infinity)
                        .contentShape(Rectangle())
                        .background(.clear)
                    }
                } action: {
                    withAnimation {
                        fullSwiped = true
                        item.onSwipe(item.id.uuidString)
                    }
                }
                .padding(.top, 8)

        }`
@c-villain, here is how I add swipes on a view that contains async image

and this is the view, that contains it

`    private var contentView: some View {
        HStack(
            alignment: .center,
            spacing: Guides.horizontalSpacing
        ) {
            image
            textFields
        }
        .padding(.horizontal, Guides.horizontalSpacing)
        .background(Colors.Gray.five)
    }`

**Comment by andrey-pagin** [comment]
@c-villain, you are right, ItemView contains AsyncImage. I've just tried to add frames to the image, and to ItemView, it didn't help.

**Comment by andrey-pagin** [comment]
I tried to use KingFisher instead of AsyncImage, it didn't work either.

**Comment by andrey-pagin** [comment]
I found wha causes this behavior. 
```
                if true {
                    EmptyView()
                }
```
I put this into the cell, the measure size func don't work.

**Comment by c-villain** [comment]
@andrey-pagin share the code  plz where u r using this EmptyView... Basically behavior for `measureSize` is expected cause there is no size for `EmptyView` 🤷🏼‍♂️

**Comment by andrey-pagin** [comment]
@c-villain You are absolutly right, but when I add 
```
    private var firstLine: some View {
        HStack {
            Text(data.title)
                .foregroundColor(Colors.Black.one)
                .font(Font.footnote.weight(.semibold))
            Spacer()
            Text(data.caption)
                .foregroundColor(Colors.Gray.two)
                .font(Font.footnote.weight(.semibold))
                if (data.isUnread) {
                    Circle().fill(Colors.Orange.one).frame(height: 8)
                }
        }
```
to the swipable view, measure size doesn't work. 

The point is that even when I add "if true {}" it doesn't work either

Thanks!

**Comment by andrey-pagin** [comment]
@c-villain 
here's example when swipes are not working, you can try by yourself 
```
import SwiftUI
import SwipeActions

struct ContentView: View {
    
    @State var swipeState: SwipeState = .untouched
    
    var body: some View {
        scrollView
    }
    
    var scrollView: some View {
        ScrollView {
            content
        }
    }
    
    var content: some View {
        ForEach(0 ..< 100) { number in
            item
                .addFullSwipeAction(
                    menu: .slided,
                    swipeColor: .blue,
                    swipeRole: .destructive,
                    state: $swipeState) {
                        Leading {
                            Button {
                            } label: {
                                Image(systemName: "archivebox")
                                    .foregroundColor(.green)
                            }
                            .frame(width: 60)
                            .frame(maxHeight: .infinity)
                            .contentShape(Rectangle())
                            .background(.clear)
                        }
                        Trailing {
                            Button {
                            } label: {
                                Image(systemName: "archivebox")
                                    .foregroundColor(.white)
                            }
                            .frame(width: 60)
                            .frame(maxHeight: .infinity)
                            .contentShape(Rectangle())
                            .background(.clear)
                        }
                    } action: {
                        print("Swiped")
                    }
        }
    }
    
    var item: some View {
        VStack {
            if false { Rectangle() }
            Text("swipe me")
                .padding(.horizontal, 20)
                .padding(.vertical, 30)
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

**Comment by andrey-pagin** [comment]
@c-villain 
I found the fix, check the PR please.

**Comment by c-villain** [comment]
@andrey-pagin thx for contributing! I'll check it soon =)

**Comment by c-villain** [comment]
✅ done in [0.3.3](https://github.com/c-villain/SwipeActions/releases/tag/0.3.3)
