### ISSUE TITLE
Adding cocoapods support

### ISSUE THREAD

**Issue by agruchala** [c-villain/SwipeActions#17]
Hi, can we add cocoapods support? If I create pull request, will You publish it to spec repo?

**Comment by c-villain** [comment]
@agruchala  Hi! Yeap =) 
Thx for ur future contributing!👍🏻

**Comment by agruchala** [comment]
Cool, I’ll do the required changes today, You can publish then to podspec
repo :)

W dniu pt., 12.05.2023 o 13:06 Alexander Kraev ***@***.***>
napisał(a):

**Comment by agruchala** [comment]
#18 is Waiting :)

**Comment by agruchala** [comment]
Hello:) Do You need help with that?

**Comment by c-villain** [comment]
✅ done
