### ISSUE TITLE
Problem with resetting the swiped cells after tapping anywhere else on the screen.

### ISSUE THREAD

**Issue by srinivas-2611** [c-villain/SwipeActions#19]
Hi!

This lib works perfectly for my app. Just wanted to know if there is any way to reset the swipe(.untouched) after tapping anywhere on the screen for the swiped cells.

**Comment by c-villain** [comment]
@srinivas-2611  Hi! Thanks for ur words!

You may use approach as in #12 

```swift
.onTapGesture {
     withAnimation {
        state = .swiped(UUID()) // <== LOOK HERE!
    }
}
```
 u should emulate swiping for some UUID() 😊

**Comment by EngOmarElsayed** [comment]
Thanks this works and helps @c-villain

**Comment by c-villain** [comment]
@EngOmarElsayed thx for ur report =)
