### ISSUE TITLE
SwipeState should update

### ISSUE THREAD

**Issue by jostster** [c-villain/SwipeActions#20]
Shouldn't the `state` for `SwipeState` update when a cell is swiped? It looks like the code is just comparing the tag's with the `id` so if we add logic to check if a cell is already swiped, the state is still `.untouched`.

**Comment by c-villain** [comment]
@jostster 

> so if we add logic to check if a cell is already swiped, the state is still `.untouched`.

What do u mean? Plz share the code...

> is just comparing the tag's with the id

Not quite so...  see the logic in this code `.valueChanged(of: dragGestureActive)`  in `SwipeActions.swift`

**Comment by c-villain** [comment]
@jostster yeap, confirmed, try to fix it =)

**Comment by c-villain** [comment]
fix in 0.3.4
