### ISSUE TITLE
Automatic closing does not work with LazyVStack items that are offscreen

### ISSUE THREAD

**Issue by gomigbg** [c-villain/SwipeActions#21]
Using the state parameter as described in the documentation, we can automatically close swiped items when a new item is swiped, however, this doesn't work in a LazyVStack.

To repro:
1. embed a LazyVStack in a ScrollView.
2. Then add enough items to the LazyVStack so that it overflows the screen. 
3. Scroll to the bottom item and open it's swipe menu.
4. Scroll the bottom item off the screen and swipe a new item
5. Scroll to the bottom item and notice that its swipe menu is still open (so now there are two items with swipe menus open)

**Comment by c-villain** [comment]
@gomigbg thx for your report👍🏻 what's iOS version for the  repro?:)

**Comment by gomigbg** [comment]
I've reproduced this on iOS 17

**Comment by c-villain** [comment]
@gomigbg  yeap, confirmed, thx for reporting!

**Comment by gomigbg** [comment]
@c-villain Great, thanks for having a look at it!

**Comment by frol86** [comment]
Works for me

<img width="884" alt="Screenshot 2024-04-21 at 12 05 11 AM" src="https://github.com/c-villain/SwipeActions/assets/56671206/6f3168c5-de19-42ed-b4ff-26e94d9fb6de">

**Comment by c-villain** [comment]
fix in 0.3.4
