### ISSUE TITLE
horizontal swipe detection too sensitive on iOS 18

### ISSUE THREAD

**Issue by mike-dydx** [c-villain/SwipeActions#35]
run example project in iOS 18 simulator, witness it is hard to scroll vertically. Horizontal gesture detection seems to have changed priority in iOS 18

**Comment by c-villain** [comment]
>  run example project in iOS 18 simulator, witness it is hard to scroll vertically. Horizontal gesture detection seems to have changed priority in iOS 18
> 
> 

Thanks for ur feedback! What example exactly in the demo project?

**Comment by ankitpanchotiya99138** [comment]
Same problem with me on Vertical scroll. hard to scroll.


If I click on cell item view and go another view and click on back, after that try to scroll but it's hard to scroll.

**Comment by c-villain** [comment]
@mike-dydx @ankitpanchotiya99138  yeap, confirmed. I'll fix it soon

**Comment by c-villain** [comment]
use modifier `.gestureSensitive` to control this sensitive or minimal distance for dragging
