### ISSUE TITLE
pretty nasty layout issue

### ISSUE THREAD

**Issue by osheroff** [c-villain/SwipeActions#38]
![IMG_F5CE8CFF7400-1](https://github.com/user-attachments/assets/493369c2-4bc8-46be-b59e-967660529757)

I tried to get a hierarchy out of the debug navigator but it simply didn't work in swiftui.

In fact, I have no idea how to get a repro into your hands.

Sorry about the paucity of this bug report.  Maybe it's my fault, I couldn't tell you.

thanks?

**Comment by c-villain** [comment]
@osheroff hi! I think u r using transparent color for layer. U should check my [recommendation](https://github.com/c-villain/SwipeActions#recommendations-for-use) (using with transparent colored views) for this.

**Comment by osheroff** [comment]
<img width="445" alt="Screenshot 2024-12-29 at 10 31 47 PM" src="https://github.com/user-attachments/assets/9580f1ca-c626-4061-9df7-58eaf6d8fe14" />

i'm getting closer.  finding the right view to dangle this of.  I can't attach it to the outermost view due to how I'm rendering stuff.  easy to manually space it out a bit?

**Comment by osheroff** [comment]
if I add:

```
            .addSwipeAction(edge: .trailing) { // <= choose here .trailing or .leading
                HStack(spacing: 0) {
                    ...
                }
                .padding(EdgeInsets(top: 0, leading: 60, bottom: 0, trailing: 0))
```

I get close, but you can see the swipe-buttons when the ui first loads -- they "run out of the way".  hmph.

**Comment by c-villain** [comment]
Please read for all [recommendations](https://github.com/c-villain/SwipeActions#recommendations-for-use)

You should add` .frame(maxWidth: .infinity)` to your Text (with I'm a note)

**Comment by osheroff** [comment]
<img width="394" alt="Screenshot 2024-12-29 at 11 41 38 PM" src="https://github.com/user-attachments/assets/5e7da27f-31b7-45f6-ba0a-2503fe222fdf" />


nope, that's not the solution, and it screws up the text.... but it's ok, i'll maybe mess around with it until i find something; i have a weird recursive view hierarchy that must be confusing the library somehow.. or padding somewhere, or something.

**Comment by c-villain** [comment]
@osheroff  plz attach ur code) it's very difficult to suggest a solution without seeing the code)

**Comment by osheroff** [comment]
@c-villain excerpting it is a bit much but I invited you to the private repo if you want to look -- the issue shows up in the SwiftUI preview of `NoteIndex`

**Comment by osheroff** [comment]
sorry, on the ben/swipe branch

**Comment by osheroff** [comment]
ok i got this sort of better my moving around where i was putting my `.padding`... but there's still the odd issue where I see a flash of the buttons while the view loads.  any ideas on a way around that?

**Comment by osheroff** [comment]
had to turn off animations on a container.  just FYI.
