### ISSUE TITLE
Incorrect displaying of 2 (or more) swipe actions on iOS 14.

### ISSUE THREAD

**Issue by Inxel** [c-villain/SwipeActions#4]
Second swipe action always displays on a row (1 screenshot). On iOS 15 it works correctly (2 screenshot).
<img width="352" alt="image" src="https://user-images.githubusercontent.com/49271404/170996767-f8b1708b-244b-4bfe-b785-3133bf9a4a4f.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/49271404/170997224-c278270f-49c7-419e-8edc-c40f5524ba6e.png">

**Comment by Inxel** [comment]
Also when I use `swiped` menu style it shows only one action after swipe (if a view is transparent, I can see all of actions under the view). Thanks for the answer!

**Comment by c-villain** [comment]
@Inxel  seems, that we fixed this in new pr, plz wait for new release

**Comment by c-villain** [comment]
fixed

**Comment by c-villain** [comment]
Add recommendations to use with transparent views in readme
